services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    image: mohamedbadr119/rails_websocket:latest
    volumes:
      - .:/app
    command: > 
      sh -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 200M
    networks:
      - websocket_random_network

  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
    networks:
      - websocket_random_network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    networks:
      - websocket_random_network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 100M

networks:
  websocket_random_network:
    driver: bridge