services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    image: mohamedbadr119/rails_websocket:latest
    volumes:
      - .:/app
    command: > 
      sh -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=development
    ports:
      - "3000:3000"
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    networks:
      - websocket_random_network
  
networks:
  websocket_random_network:
    driver: bridge