services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    image: mohamedbadr119/rails_websocket:latest
    volumes:
      - .:/app
    command: > 
      sh -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 200M
    networks:
      - websocket_random_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
    networks:
      - websocket_random_network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M

  nginx:
    container_name: nginx_proxy
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
    networks:
      - websocket_random_network

networks:
  websocket_random_network:
    driver: bridge